export const defaultValuesSample = {
  tb_1_clay: 0,
  tb_1_silt: 0,
  tb_1_sand: 0,
  tb_2_organic_matter: 0,
  tb_2_ph: 0,
  tb_3_p_phosphor: 0,
  tb_3_k_potassium: 0,
  tb_3_na_sodium: 0,
  tb_3_s_sulfur: 0,
  tb_3_b_boron: 0,
  tb_3_cu_copper: 0,
  tb_3_fe_iron: 0,
  tb_3_mn_manganese: 0,
  tb_3_zn_zinc: 0,
  tb_4_ca_calcium: 0,
  tb_4_mg_magnesium: 0,
  tb_4_al_aluminum: 0,
  tb_4_h_al_potential_acidity: 0,
}
